# Generated by Django 5.1.2 on 2024-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
