# Generated by Django 5.1.2 on 2025-01-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_shoe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
    ]
